### ISSUE TITLE
react-factory-hooks production ready status.

### ISSUE THREAD

**Issue by artalar** [PutziSan/react-factory-hooks#4]
factory hooks is a good idea. I understand that is mostly proposal, but you already have the implementation, so it is production ready or not? Will you work on it and support as production library?

**Comment by PutziSan** [comment]
Hi @artalar, the current implementation depends on a global variable that is overwritten repeatedly in the constructor of a class-component (the HOC).  If 2 components are initialized at the same time, one constructor would overwrite the variable and the factory component would no longer work.  I don't think this is currently possible in React, so even this implementation _should_ currently work in a more complex app. 

I could imagine that it doesn't work with concurrent react, because the name itself indicates that components could be called at the same time. In order to answer these questions, one would have to dive deeper into React or involve someone from the react team, and unfortunately I don't have time for that at the moment.

However, the current implementation is 132 lines of code and quite quick to survey. So if you see a use case for it, you are welcome to test it in a more complex app and tell me about your experiences, if there are any problems, I will be happy to help.
